### ISSUE TITLE
Error on sample data. ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by chanjuping** [nyorem/python-japanese-ocr#1]
On an Ubuntu 20.04 fresh virtual machine setup with 4 GB RAM and 6 Cores, I ran through a the setup process, and also installed python3-scipy as a dependency.

Running `./main.py examples/sample_page.jpg`, I got:

> Analyzing image=examples/sample_page.jpg...
> Saving results to results_sample_page
> Traceback (most recent call last):
>   File "./main.py", line 228, in <module>
>     sections = analyse_image(img, verbose=verbose, dirname=dirname)
>   File "./main.py", line 166, in analyse_image
>     sections = find_sections(img, verbose=verbose, dirname=dirname)
>   File "./main.py", line 81, in find_sections
>     ctrs = find_contours_text(img, size, verbose=verbose, sort_key=sort_key)
>   File "./main.py", line 36, in find_contours_text
>     _, ctrs, _ = cv2.findContours(dilation.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: not enough values to unpack (expected 3, got 2)

I initially found this error in my Opensuse Tumbleweed host machine as well.

> Analyzing image=examples/sample_page.jpg...
> Saving results to results_sample_page
> Traceback (most recent call last):
>   File "./main.py", line 228, in <module>
>     sections = analyse_image(img, verbose=verbose, dirname=dirname)
>   File "./main.py", line 166, in analyse_image
>     sections = find_sections(img, verbose=verbose, dirname=dirname)
>   File "./main.py", line 81, in find_sections
>     ctrs = find_contours_text(img, size, verbose=verbose, sort_key=sort_key)
>   File "./main.py", line 36, in find_contours_text
>     _, ctrs, _ = cv2.findContours(dilation.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Piturnah** [comment]
I am having this same issue on Windows 10

**Comment by Ghost99** [comment]
This is because of this particular commit: bfa3ee78ca682b603bc36e86623c5f32bc202d00
Just remove first argument in https://github.com/nyorem/python-japanese-ocr/blob/bfa3ee78ca682b603bc36e86623c5f32bc202d00/main.py#L36
and it will work
